# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vnrjm74Qh7EPpHh2fDZabQmX4HnkinPq
"""

from setuptools import setup, find_packages

setup(
  name="nnscratch",
  version="0.1.0",
  description="Neural‐net‐from‐scratch toolkit for NLP tasks",
  author="Lyu CHEN, Shuyue GU, Varvara SMIRNOVA",
  packages=find_packages(),
  install_requires=[
    "cupy",
    "numpy",
  ],
  python_requires=">=3.7",
)

