# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vnrjm74Qh7EPpHh2fDZabQmX4HnkinPq
"""

# setup.py

from setuptools import setup, find_packages

setup(
    name="nnscratch",
    version="0.1.0",
    description="Neural‐network‐from‐scratch toolkit for NLP tasks (POS tagging, etc.)",
    author="Lyu CHEN, Shuyue GU, Varvara SMIRNOVA",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.20"
    ],
    extras_require={
        # GPU users can optionally install CuPy for accelerated array ops:
        "gpu": ["cupy"]
    },
    python_requires=">=3.7",
)

